#!/usr/bin/env python3
"""Generates the synthetic dot-grid fixtures used by test/skin-signature.test.js.
Run manually with the project's venv if fixtures ever need regenerating:
    venv/bin/python3 test/fixtures/generate-periodic-test-image.py
"""
import os
import cv2
import numpy as np

fixtures_dir = os.path.dirname(__file__)


def make_dot_grid(spacing_px, angle_deg, size=256, dot_radius=2):
    """A grid of filled dots at `spacing_px` apart, rotated `angle_deg`
    degrees. Generated by placing dots along a rotated lattice directly
    (rather than rotating a finished image), so there are no black border
    artifacts to worry about."""
    img = np.full((size, size), 255, dtype=np.uint8)
    theta = np.radians(angle_deg)
    u = np.array([np.cos(theta), np.sin(theta)]) * spacing_px
    v = np.array([-np.sin(theta), np.cos(theta)]) * spacing_px
    center = np.array([size / 2, size / 2])
    n = int(size / spacing_px) + 4
    for i in range(-n, n):
        for j in range(-n, n):
            point = center + i * u + j * v
            x, y = int(round(point[0])), int(round(point[1]))
            if 0 <= x < size and 0 <= y < size:
                cv2.circle(img, (x, y), dot_radius, 0, -1)
    return img


cv2.imwrite(os.path.join(fixtures_dir, "test-grid-10px.png"), make_dot_grid(10, 0))
cv2.imwrite(os.path.join(fixtures_dir, "test-grid-20px.png"), make_dot_grid(20, 0))
cv2.imwrite(os.path.join(fixtures_dir, "test-grid-10px-rotated.png"), make_dot_grid(10, 30))

print("wrote test-grid-10px.png, test-grid-20px.png, test-grid-10px-rotated.png")
