import { attachCalibration } from './calibration-ui.js';
import { attachRegionSelect } from './region-select-ui.js';
import { boundingBox, polygonArea } from './nesting/geometry.js';
import { compareByColour } from './skins/colour-order.js';
import { populateSpeciesSelect } from './skins/species.js';

const summaryEl = document.getElementById('hides-summary');
const gridEl = document.getElementById('hide-grid');
const searchInput = document.getElementById('hide-search');
const sortInput = document.getElementById('hide-sort');
const speciesTagsEl = document.getElementById('species-tags');

const openAddButton = document.getElementById('open-add-hide');
const cancelAddButton = document.getElementById('cancel-add-hide');
const submitButton = document.getElementById('submit-hide');
const dialog = document.getElementById('add-hide-dialog');
const labelInput = document.getElementById('hide-label');
const speciesInput = document.getElementById('hide-species');
const thicknessInput = document.getElementById('hide-thickness');
const finishInput = document.getElementById('hide-finish');
const photoInput = document.getElementById('hide-photo');
const calibrationContainer = document.getElementById('hide-calibration-container');
const regionContainer = document.getElementById('hide-region-container');
const forMatchingInput = document.getElementById('hide-for-matching');
const matchingRegionWrapper = document.getElementById('hide-matching-region-wrapper');
const matchingRegionContainer = document.getElementById('hide-matching-region-container');
const addStatus = document.getElementById('add-hide-status');

populateSpeciesSelect(speciesInput);

const redigitizeDialog = document.getElementById('redigitize-dialog');
const redigitizePhotoInput = document.getElementById('redigitize-photo');
const redigitizeCalibrationContainer = document.getElementById('redigitize-calibration-container');
const redigitizeRegionContainer = document.getElementById('redigitize-region-container');
const redigitizeStatus = document.getElementById('redigitize-status');
const cancelRedigitizeButton = document.getElementById('cancel-redigitize');
const submitRedigitizeButton = document.getElementById('submit-redigitize');

const measureDialog = document.getElementById('measure-dialog');
const measureCalibrationContainer = document.getElementById('measure-calibration-container');
const measureRegionContainer = document.getElementById('measure-region-container');
const measureStatus = document.getElementById('measure-status');
const cancelMeasureButton = document.getElementById('cancel-measure');
const submitMeasureButton = document.getElementById('submit-measure');

const deleteDialog = document.getElementById('delete-dialog');
const deleteSummary = document.getElementById('delete-summary');
const deleteLosses = document.getElementById('delete-losses');
const deleteJobsWarning = document.getElementById('delete-jobs-warning');
const cancelDeleteButton = document.getElementById('cancel-delete');
const confirmDeleteButton = document.getElementById('confirm-delete');

let hides = [];
let selectedSpecies = null;
let selectedPhoto = null;
let calibration = null;
let region = null;
// The scale-pattern patch, marked separately from the outline region. The two
// regions answer different questions -- "where is the hide" vs "where is a
// clean stretch of scales" -- so reusing one box for both would hand
// skin_signature.py a region nobody chose for it.
let matchingRegion = null;
let redigitizeHideId = null;
let redigitizePhoto = null;
let redigitizeCalibration = null;
let redigitizeRegion = null;
let measureHideId = null;
let measureCalibration = null;
let measureRegion = null;
let deleteHideId = null;
// The last value the auto-namer itself wrote into the label field. Lets it
// tell "still mine to update" apart from "the operator typed over this" --
// comparing against the empty string alone would re-overwrite a name the
// operator deliberately cleared.
let lastAutoGeneratedName = '';

function escapeHtml(str) {
  return str.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

function hideSizeLabel(hide) {
  if (!hide.outlinePolygon) return '—';
  const b = boundingBox(hide.outlinePolygon);
  const width = Math.round(b.maxX - b.minX);
  const height = Math.round(b.maxY - b.minY);
  return `${width} × ${height} mm`;
}

function hideFootprintAreaMm2(hide) {
  if (!hide.outlinePolygon) return 0;
  return polygonArea(hide.outlinePolygon);
}

// CIE LAB (D65) -> sRGB, for showing the sampled colour as a swatch. Standard
// conversion, not calibrated against a spectrophotometer -- good enough for
// "does this look like the leather," not for judging exact hex values.
function labToCss(l, a, b) {
  const fy = (l + 16) / 116;
  const fx = fy + a / 500;
  const fz = fy - b / 200;
  const finv = (t) => (t ** 3 > 0.008856 ? t ** 3 : (t - 16 / 116) / 7.787);
  const x = 0.95047 * finv(fx);
  const y = finv(fy);
  const z = 1.08883 * finv(fz);

  const toSrgb = (c) => (c > 0.0031308 ? 1.055 * c ** (1 / 2.4) - 0.055 : 12.92 * c);
  const r = toSrgb(x * 3.2406 + y * -1.5372 + z * -0.4986);
  const g = toSrgb(x * -0.9689 + y * 1.8758 + z * 0.0415);
  const bl = toSrgb(x * 0.0557 + y * -0.204 + z * 1.057);

  const clamp = (c) => Math.max(0, Math.min(255, Math.round(c * 255)));
  return `rgb(${clamp(r)}, ${clamp(g)}, ${clamp(bl)})`;
}

function resetAddForm() {
  labelInput.value = '';
  speciesInput.value = '';
  thicknessInput.value = '';
  finishInput.value = '';
  photoInput.value = '';
  calibrationContainer.innerHTML = '';
  regionContainer.innerHTML = '';
  matchingRegionContainer.innerHTML = '';
  matchingRegionWrapper.hidden = true;
  forMatchingInput.checked = false;
  addStatus.textContent = '';
  selectedPhoto = null;
  calibration = null;
  region = null;
  matchingRegion = null;
  lastAutoGeneratedName = '';
}

// The patch selector only appears once there's a photo to drag on, and it is
// rebuilt each time it's shown -- attachRegionSelect clears the container it
// is handed, so re-attaching on an empty one would leave nothing to click.
function refreshMatchingRegionSelect() {
  const wanted = forMatchingInput.checked && selectedPhoto !== null;
  matchingRegionWrapper.hidden = !wanted;
  if (!wanted) {
    matchingRegion = null;
    matchingRegionContainer.innerHTML = '';
    return;
  }
  attachRegionSelect(matchingRegionContainer, URL.createObjectURL(selectedPhoto), (result) => {
    matchingRegion = result;
  });
}

forMatchingInput.addEventListener('change', refreshMatchingRegionSelect);

// species/thickness/finish, each abbreviated to two characters -- the ten
// species on the dropdown all differ in their first two letters, so no
// lookup table is needed, and the same holds for the three finish values.
// Segments for a field not filled in yet are simply omitted, so the name
// builds up as the operator fills the form rather than showing blanks.
function hideNameParts() {
  const parts = [];
  if (speciesInput.value) parts.push(speciesInput.value.slice(0, 2).toUpperCase());
  const thicknessMm = Number(thicknessInput.value);
  if (Number.isFinite(thicknessMm) && thicknessMm > 0) {
    // Tenths of a mm as two digits (1.2mm -> "12") rather than rounding to
    // a whole mm, which would collide constantly -- most of this project's
    // real thicknesses sit between 1.0 and 2.5mm.
    parts.push(String(Math.round(thicknessMm * 10)).padStart(2, '0'));
  }
  if (finishInput.value) parts.push(finishInput.value.slice(0, 2).toUpperCase());
  return parts;
}

// A date fragment beats a bare counter as the tie-breaker: two hides with
// the same species/thickness/finish added on different days are quite
// possibly a different dye lot, which is worth the name saying outright.
// The counter below still exists for the rarer case of two matching that on
// the same day too.
function dateCode() {
  const now = new Date();
  return String(now.getMonth() + 1).padStart(2, '0') + String(now.getDate()).padStart(2, '0');
}

function generateHideName() {
  const parts = hideNameParts();
  if (parts.length === 0) return '';
  parts.push(dateCode());

  const base = parts.join('-');
  const existingLabels = new Set(hides.map((h) => h.label));
  if (!existingLabels.has(base)) return base;
  for (let suffix = 2; ; suffix++) {
    const candidate = `${base}-${suffix}`;
    if (!existingLabels.has(candidate)) return candidate;
  }
}

// Only touches the name field while it still holds what THIS function wrote
// last time (or is empty) -- the moment the operator types their own name
// over it, every later field change leaves it alone.
function maybeAutoGenerateName() {
  if (labelInput.value !== '' && labelInput.value !== lastAutoGeneratedName) return;
  lastAutoGeneratedName = generateHideName();
  labelInput.value = lastAutoGeneratedName;
}

openAddButton.addEventListener('click', () => {
  dialog.hidden = false;
});

speciesInput.addEventListener('change', maybeAutoGenerateName);
thicknessInput.addEventListener('input', maybeAutoGenerateName);
finishInput.addEventListener('change', maybeAutoGenerateName);

cancelAddButton.addEventListener('click', () => {
  dialog.hidden = true;
  resetAddForm();
});

photoInput.addEventListener('change', () => {
  const file = photoInput.files[0];
  if (!file) return;
  selectedPhoto = file;
  calibration = null;
  region = null;
  regionContainer.innerHTML = '';
  refreshMatchingRegionSelect();

  const objectUrl = URL.createObjectURL(file);
  attachCalibration(calibrationContainer, objectUrl, (calibrationResult) => {
    calibration = calibrationResult;
    attachRegionSelect(regionContainer, objectUrl, (regionResult) => {
      region = regionResult;
    });
  });
});

submitButton.addEventListener('click', async () => {
  const label = labelInput.value.trim();
  const species = speciesInput.value.trim();
  const thicknessMm = thicknessInput.value;

  if (!label || !species || !thicknessMm) {
    addStatus.textContent = 'Name, species, and thickness are required.';
    return;
  }
  if (!selectedPhoto || !calibration) {
    addStatus.textContent = 'Upload a photo and complete calibration first.';
    return;
  }
  if (forMatchingInput.checked && !matchingRegion) {
    addStatus.textContent =
      'Drag a patch of scales to measure, or untick "Also measure this hide for matching".';
    return;
  }

  const formData = new FormData();
  formData.append('captureType', 'outline');
  formData.append('label', label);
  formData.append('species', species);
  formData.append('thicknessMm', thicknessMm);
  if (finishInput.value) formData.append('finish', finishInput.value);
  formData.append('photo', selectedPhoto);
  formData.append('p1x', calibration.p1x);
  formData.append('p1y', calibration.p1y);
  formData.append('p2x', calibration.p2x);
  formData.append('p2y', calibration.p2y);
  formData.append('realDistanceMm', calibration.realDistanceMm);
  if (region) {
    formData.append('roiX', region.roiX);
    formData.append('roiY', region.roiY);
    formData.append('roiWidth', region.roiWidth);
    formData.append('roiHeight', region.roiHeight);
  }
  if (matchingRegion) {
    formData.append('captureForMatching', 'true');
    formData.append('matchRoiX', matchingRegion.roiX);
    formData.append('matchRoiY', matchingRegion.roiY);
    formData.append('matchRoiWidth', matchingRegion.roiWidth);
    formData.append('matchRoiHeight', matchingRegion.roiHeight);
  }

  addStatus.textContent = 'Adding…';

  try {
    const response = await fetch('/skins', { method: 'POST', body: formData });
    const body = await response.json();
    if (!response.ok) {
      addStatus.textContent = `Error: ${body.error}`;
      return;
    }
    // The hide is saved either way -- a scale patch that couldn't be measured
    // costs the matching entry, not the hide. Leave the dialog open so the
    // warning gets read instead of flashing past.
    if (body.warning) {
      addStatus.textContent = body.warning;
      await loadHides();
      return;
    }
    dialog.hidden = true;
    resetAddForm();
    await loadHides();
  } catch {
    addStatus.textContent = 'Error: could not reach the server. Please try again.';
  }
});

function resetRedigitizeForm() {
  redigitizeHideId = null;
  redigitizePhoto = null;
  redigitizeCalibration = null;
  redigitizeRegion = null;
  redigitizePhotoInput.value = '';
  redigitizeCalibrationContainer.innerHTML = '';
  redigitizeRegionContainer.innerHTML = '';
  redigitizeStatus.textContent = '';
}

redigitizePhotoInput.addEventListener('change', () => {
  const file = redigitizePhotoInput.files[0];
  if (!file) return;
  redigitizePhoto = file;
  redigitizeCalibration = null;
  redigitizeRegion = null;
  redigitizeRegionContainer.innerHTML = '';

  const objectUrl = URL.createObjectURL(file);
  attachCalibration(redigitizeCalibrationContainer, objectUrl, (calibrationResult) => {
    redigitizeCalibration = calibrationResult;
    attachRegionSelect(redigitizeRegionContainer, objectUrl, (regionResult) => {
      redigitizeRegion = regionResult;
    });
  });
});

cancelRedigitizeButton.addEventListener('click', () => {
  redigitizeDialog.hidden = true;
  resetRedigitizeForm();
});

submitRedigitizeButton.addEventListener('click', async () => {
  if (!redigitizeHideId || !redigitizePhoto || !redigitizeCalibration) {
    redigitizeStatus.textContent = 'Upload a photo and complete calibration first.';
    return;
  }

  const formData = new FormData();
  formData.append('photo', redigitizePhoto);
  formData.append('p1x', redigitizeCalibration.p1x);
  formData.append('p1y', redigitizeCalibration.p1y);
  formData.append('p2x', redigitizeCalibration.p2x);
  formData.append('p2y', redigitizeCalibration.p2y);
  formData.append('realDistanceMm', redigitizeCalibration.realDistanceMm);
  if (redigitizeRegion) {
    formData.append('roiX', redigitizeRegion.roiX);
    formData.append('roiY', redigitizeRegion.roiY);
    formData.append('roiWidth', redigitizeRegion.roiWidth);
    formData.append('roiHeight', redigitizeRegion.roiHeight);
  }

  redigitizeStatus.textContent = 'Updating…';

  try {
    const response = await fetch(`/skins/${redigitizeHideId}/redigitize`, { method: 'POST', body: formData });
    const body = await response.json();
    if (!response.ok) {
      redigitizeStatus.textContent = `Error: ${body.error}`;
      return;
    }
    redigitizeDialog.hidden = true;
    resetRedigitizeForm();
    await loadHides();
  } catch {
    redigitizeStatus.textContent = 'Error: could not reach the server. Please try again.';
  }
});

function resetMeasureForm() {
  measureHideId = null;
  measureCalibration = null;
  measureRegion = null;
  measureCalibrationContainer.innerHTML = '';
  measureRegionContainer.innerHTML = '';
  measureStatus.textContent = '';
}

// Works off the hide's stored photo rather than a fresh upload -- it is the
// same hide, and re-shooting it is what "Update remaining shape" is for. The
// calibration has to be marked again because it is never stored on a hide.
function openMeasureDialog(hideId) {
  resetMeasureForm();
  measureHideId = hideId;
  measureDialog.hidden = false;
  const photoUrl = `/skins/${hideId}/photo`;
  attachCalibration(measureCalibrationContainer, photoUrl, (calibrationResult) => {
    measureCalibration = calibrationResult;
    attachRegionSelect(measureRegionContainer, photoUrl, (regionResult) => {
      measureRegion = regionResult;
    });
  });
}

cancelMeasureButton.addEventListener('click', () => {
  measureDialog.hidden = true;
  resetMeasureForm();
});

submitMeasureButton.addEventListener('click', async () => {
  if (!measureHideId || !measureCalibration || !measureRegion) {
    measureStatus.textContent = 'Mark the calibration points, then drag a patch of scales.';
    return;
  }

  const formData = new FormData();
  formData.append('p1x', measureCalibration.p1x);
  formData.append('p1y', measureCalibration.p1y);
  formData.append('p2x', measureCalibration.p2x);
  formData.append('p2y', measureCalibration.p2y);
  formData.append('realDistanceMm', measureCalibration.realDistanceMm);
  formData.append('roiX', measureRegion.roiX);
  formData.append('roiY', measureRegion.roiY);
  formData.append('roiWidth', measureRegion.roiWidth);
  formData.append('roiHeight', measureRegion.roiHeight);

  measureStatus.textContent = 'Measuring…';

  try {
    const response = await fetch(`/skins/${measureHideId}/signature`, {
      method: 'POST',
      body: formData,
    });
    const body = await response.json();
    if (!response.ok) {
      measureStatus.textContent = `Error: ${body.error}`;
      return;
    }
    measureDialog.hidden = true;
    resetMeasureForm();
    await loadHides();
  } catch {
    measureStatus.textContent = 'Error: could not reach the server. Please try again.';
  }
});

// Names what is actually about to be destroyed. A confirmation that only
// asks "are you sure?" trains the reflex it is meant to interrupt -- the
// friction has to carry information, or it is just an extra click.
function describeLosses(hide) {
  const losses = ['The photo of this hide'];
  if (hide.outlinePolygon) losses.push('Its traced outline and measured size');
  if (hide.colourL != null) losses.push('Its sampled colour');
  if (hide.dominantWavelengthMm != null) {
    losses.push(`Its scale measurement (${hide.dominantWavelengthMm.toFixed(2)}mm) — it would drop out of matching`);
  }
  const remaining = hide.remainingAreaPct ?? 100;
  if (remaining < 100) {
    losses.push(`The record that ${Math.round(100 - remaining)}% of it has already been cut`);
  }
  return losses;
}

async function openDeleteDialog(hideId) {
  const hide = hides.find((h) => h.id === hideId);
  if (!hide) return;

  deleteHideId = hideId;
  deleteSummary.innerHTML = `<strong>${escapeHtml(hide.label)}</strong> — ${escapeHtml(hide.species)}, ${hideSizeLabel(hide)}.`;
  deleteLosses.innerHTML = describeLosses(hide)
    .map((loss) => `<li>${escapeHtml(loss)}</li>`)
    .join('');
  deleteJobsWarning.hidden = true;
  deleteJobsWarning.textContent = '';
  deleteDialog.hidden = false;

  // Looked up only when the dialog opens, not on every page load -- it costs
  // a request, and it matters in the one moment before something becomes
  // irreversible. Jobs survive their hide being deleted, but they lose the
  // trace of what was cut from what.
  try {
    const sessions = await (await fetch('/sessions')).json();
    const linked = sessions.filter((session) => session.hideId === hideId);
    if (linked.length > 0 && deleteHideId === hideId) {
      const cut = linked.filter((session) => session.status === 'cut').length;
      deleteJobsWarning.textContent =
        `${linked.length} job${linked.length === 1 ? '' : 's'} reference${linked.length === 1 ? 's' : ''} this hide` +
        `${cut > 0 ? ` (${cut} already cut)` : ''}. They will keep working, but will no longer say which hide they came from.`;
      deleteJobsWarning.hidden = false;
    }
  } catch {
    // A failed lookup must not block the decision -- the dialog still states
    // everything else that is lost.
  }
}

cancelDeleteButton.addEventListener('click', () => {
  deleteDialog.hidden = true;
  deleteHideId = null;
});

confirmDeleteButton.addEventListener('click', async () => {
  if (!deleteHideId) return;
  const id = deleteHideId;
  confirmDeleteButton.disabled = true;
  try {
    await fetch(`/skins/${id}`, { method: 'DELETE' });
    deleteDialog.hidden = true;
    deleteHideId = null;
    await loadHides();
  } finally {
    confirmDeleteButton.disabled = false;
  }
});

// Each option carries the one direction that answers the question someone
// picked it to ask -- "most remaining" and "largest" are what you look for
// when hunting material, so those run high-to-low, while species and
// thickness read naturally low-to-high.
//
// A hide with no thickness recorded sorts last rather than as zero, which
// would park signature-only hides at the front of the thinnest-first list.
// Sort is stable, so ties keep the server's date order underneath.
const SORTS = {
  added: (a, b) => a.createdAt.localeCompare(b.createdAt),
  remaining: (a, b) => (b.remainingAreaPct ?? 100) - (a.remainingAreaPct ?? 100),
  size: (a, b) => hideFootprintAreaMm2(b) - hideFootprintAreaMm2(a),
  colour: compareByColour,
  species: (a, b) => a.species.localeCompare(b.species),
  thickness: (a, b) => {
    if (a.thicknessMm == null && b.thicknessMm == null) return 0;
    if (a.thicknessMm == null) return 1;
    if (b.thicknessMm == null) return -1;
    return a.thicknessMm - b.thicknessMm;
  },
};

function matchesFilters(hide, query, species) {
  if (species && hide.species.trim().toLowerCase() !== species) return false;
  if (!query) return true;
  const haystack = `${hide.label} ${hide.species} ${hide.id}`.toLowerCase();
  return haystack.includes(query);
}

function renderSpeciesTags() {
  const species = [...new Set(hides.map((h) => h.species.trim().toLowerCase()))].sort();
  speciesTagsEl.innerHTML = species
    .map(
      (s) =>
        `<button type="button" class="tag ${s === selectedSpecies ? 'tag-accent' : 'tag-neutral'}" aria-pressed="${s === selectedSpecies}" data-species="${escapeHtml(s)}">${escapeHtml(s)}</button>`,
    )
    .join('');
}

function renderSummary(visible) {
  const totalAreaMm2 = visible.reduce((sum, h) => sum + hideFootprintAreaMm2(h) * ((h.remainingAreaPct ?? 100) / 100), 0);
  const totalAreaCm2 = Math.round(totalAreaMm2 / 100);
  summaryEl.textContent = `${visible.length} hide${visible.length === 1 ? '' : 's'} · ${totalAreaCm2} cm² usable`;
}

function renderGrid() {
  const query = searchInput.value.trim().toLowerCase();
  const visible = hides
    .filter((h) => matchesFilters(h, query, selectedSpecies))
    .sort(SORTS[sortInput.value] ?? SORTS.added);

  renderSummary(visible);

  gridEl.innerHTML = visible
    .map((hide) => {
      const remaining = hide.remainingAreaPct ?? 100;
      const date = new Date(hide.createdAt).toLocaleDateString();
      const swatch = hide.colourL != null
        ? `<span class="colour-swatch" style="background:${labToCss(hide.colourL, hide.colourA, hide.colourB)}" title="sampled colour"></span>`
        : '';
      // Derived, never stored: a hide is matchable exactly when it carries a
      // scale measurement, which is what the matching page filters on. A
      // separate saved flag could disagree with that, and then one of the two
      // would be lying.
      const matchable = hide.dominantWavelengthMm != null
        ? `<span class="tag tag-accent" title="${hide.dominantWavelengthMm.toFixed(2)}mm scale">matchable</span>`
        : '';
      return `
    <div class="card hide-card elev-sm">
      <img class="washed" src="/skins/${hide.id}/photo" alt="${escapeHtml(hide.label)}" />
      <div class="card-title">
        <span>${escapeHtml(hide.species)} ${swatch}</span>
        <span>${matchable}<span class="tag tag-outline">${hide.id.slice(0, 8)}</span></span>
      </div>
      <p class="card-body">${escapeHtml(hide.label)} · ${hideSizeLabel(hide)}${hide.thicknessMm != null ? ` · ${hide.thicknessMm} mm thick` : ''}${hide.finish ? ` · ${escapeHtml(hide.finish)}` : ''}</p>
      <div class="area-bar"><div class="area-bar-fill" style="width: ${Math.max(0, Math.min(100, remaining))}%"></div></div>
      <div class="card-meta">${Math.round(remaining)}% remaining · captured ${date}</div>
      <div class="card-actions">
        <button type="button" class="btn btn-secondary" data-redigitize="${hide.id}">Update remaining shape</button>
        ${hide.dominantWavelengthMm == null
          ? `<button type="button" class="btn btn-secondary" data-measure="${hide.id}">Measure for matching</button>`
          : ''}
        <button type="button" class="btn btn-secondary" data-delete="${hide.id}">Delete</button>
      </div>
    </div>
  `;
    })
    .join('');
}

async function loadHides() {
  const response = await fetch('/skins');
  hides = await response.json();
  renderSpeciesTags();
  renderGrid();
}

speciesTagsEl.addEventListener('click', (event) => {
  const species = event.target.dataset.species;
  if (!species) return;
  selectedSpecies = selectedSpecies === species ? null : species;
  renderSpeciesTags();
  renderGrid();
});

gridEl.addEventListener('click', (event) => {
  const deleteId = event.target.dataset.delete;
  if (deleteId) {
    openDeleteDialog(deleteId);
    return;
  }
  const measureId = event.target.dataset.measure;
  if (measureId) {
    openMeasureDialog(measureId);
    return;
  }
  const hideId = event.target.dataset.redigitize;
  if (!hideId) return;
  resetRedigitizeForm();
  redigitizeHideId = hideId;
  redigitizeDialog.hidden = false;
});

searchInput.addEventListener('input', renderGrid);
sortInput.addEventListener('change', renderGrid);

loadHides();
